/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haisheng_player_HsPlay */

#ifndef _Included_com_haisheng_player_HsPlay
#define _Included_com_haisheng_player_HsPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_prepare
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1prepare
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1start
  (JNIEnv *, jobject);

/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1resume
  (JNIEnv *, jobject);

/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1pause
  (JNIEnv *, jobject);

/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1stop
  (JNIEnv *, jobject);

/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_seek
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1seek
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_haisheng_player_HsPlay
 * Method:    n_seekVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_haisheng_player_HsPlay_n_1seekVolume
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
